siteName: Brewen Couaran's Portfolio
baseUrl: https://brewen.dev
defaultSeo:
  title: Brewen Couaran - Portfolio
  description: Fullstack, AI, and research portfolio.
  image: /og.png
  keywords:
    - fullstack
    - ai
    - research
    - portfolio
cvUrl: https://raw.githubusercontent.com/brewcoua/portfolio/master/static/cv.pdf
navigation:
  - label: Home
    href: /
  - label: About
    href: /about
  - label: Projects
    href: /projects
  - label: Contact
    href: /contact
